---
swagger: "2.0"
info:
  version: "0.1.0"
  title: "reco-engine-dev"
host: "dev-recommendations.dive.tv"
schemes:
- "https"
paths:
  /v1/build:
    get:
      operationId: "getBuild"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        400:
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        500:
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        401:
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        504:
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
  /v1/ping:
    get:
      operationId: "getPing"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        400:
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        500:
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        401:
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        504:
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
  /v1/profile:
    get:
      operationId: "getProfile"
      parameters:
      - name: "pageSize"
        in: "query"
        required: false
        type: "string"
      - name: "x-api-key"
        in: "header"
        required: true
        type: "string"
      - name: "externalAccountId"
        in: "query"
        required: false
        type: "string"
      - name: "page"
        in: "query"
        required: false
        type: "string"
      - name: "externalProfileId"
        in: "query"
        required: false
        type: "string"
      - name: "client-id"
        in: "header"
        required: true
        type: "string"
      - name: "id"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        400:
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        500:
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        401:
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        504:
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
    post:
      operationId: "postProfile"
      consumes:
      - "application/json; charset=utf-8"
      parameters:
      - name: "x-api-key"
        in: "header"
        required: true
        type: "string"
      - name: "client-id"
        in: "header"
        required: true
        type: "string"
      - in: "body"
        name: "MODEL648bef"
        required: true
        schema:
          $ref: "#/definitions/MODEL648bef"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        400:
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        500:
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        401:
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        504:
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
  /v1/profile/{id}:
    delete:
      operationId: "deleteProfile"
      parameters:
      - name: "x-api-key"
        in: "header"
        required: true
        type: "string"
      - name: "client-id"
        in: "header"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        400:
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        500:
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        401:
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        504:
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
    patch:
      operationId: "patchProfile"
      consumes:
      - "application/json; charset=utf-8"
      parameters:
      - name: "x-api-key"
        in: "header"
        required: true
        type: "string"
      - name: "client-id"
        in: "header"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "MODELa07b6a"
        required: true
        schema:
          $ref: "#/definitions/MODELa07b6a"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        400:
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        500:
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        401:
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        504:
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
  /v1/recommendations:
    get:
      operationId: "getRecommendations"
      parameters:
      - name: "externalAccountProfileId"
        in: "query"
        required: false
        type: "string"
      - name: "device"
        in: "query"
        required: false
        type: "string"
      - name: "contentType"
        in: "query"
        required: false
        type: "string"
      - name: "profileCountry"
        in: "query"
        required: false
        type: "string"
      - name: "pageSize"
        in: "query"
        required: false
        type: "string"
      - name: "tag"
        in: "query"
        required: false
        type: "string"
      - name: "x-api-key"
        in: "header"
        required: true
        type: "string"
      - name: "mediaEventType"
        in: "query"
        required: false
        type: "string"
      - name: "exclusivePageStart"
        in: "query"
        required: false
        type: "string"
      - name: "mediaContentProviderId"
        in: "query"
        required: false
        type: "string"
      - name: "client-id"
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        400:
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        500:
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        401:
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
        504:
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
            Content-Type:
              type: "string"
definitions:
  MODEL648bef:
    type: "object"
    required:
    - "country"
    - "enabledParentalRatings"
    - "externalAccountId"
    - "externalProfileId"
    - "name"
    - "subscriptionPackages"
    properties:
      externalProfileId:
        type: "string"
      externalAccountId:
        type: "string"
      name:
        type: "string"
      subscriptionPackages:
        type: "array"
        items:
          type: "string"
      enabledParentalRatings:
        type: "array"
        items:
          type: "object"
          properties:
            scheme:
              type: "string"
            value:
              type: "string"
      country:
        type: "string"
  MODELa07b6a:
    type: "object"
    properties:
      name:
        type: "string"
      subscriptionPackages:
        type: "array"
        items:
          type: "string"
      enabledParentalRatings:
        type: "array"
        items:
          type: "object"
          properties:
            scheme:
              type: "string"
            value:
              type: "string"
      country:
        type: "string"
