#!/bin/bash

export $(egrep -v '^#' .env | xargs)

CLONE_FOLDER=tmp/api
CUR_DIR=$(pwd)

#
#   Branch to clone
#
if [ -z "$API_BRANCH" ]
then
    $API_BRANCH = 'develop'
fi

#
#   Get the api
#
if [ -d "$CLONE_FOLDER" ]
then
    rm -rf $CLONE_FOLDER
fi

git clone https://github.com/dive-tv/reco-engine-api.git $CLONE_FOLDER
cd $CLONE_FOLDER
git checkout $API_BRANCH
npm i --production 
node ./scripts/swagger-build.js
cp generated.yml ../../swagger/api.yaml
cp generated.json ../../swagger/api.json
cd $CUR_DIR
